onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
  - unrs-resolver
nodeLinker: hoisted
confirmModulesPurge: false
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
